<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category           Netresearch
 * @package            Netresearch_JCarouselSlider
 * @author               Dandy Umlauft <dandy.umlauft@netresearch.de>
 * @copyright           Copyright (c) 2011 Dandy Umlauft | Netresearch GmbH & Co.KG (http://www.netresearch.de)
 * @license               http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
    $jcUpsell = $this->jcUpsell;
    $SliderActivation = $jcUpsell->getSliderActivation();
    $ItemCountScroll = $jcUpsell->getItemCountScroll();
    $ScrollSpeed = $jcUpsell->getScrollSpeed();
    $SliderAlignment = $jcUpsell->getSliderAlignment();
    $SliderCircular = $jcUpsell->getSliderCircular();
    $AutoScrollTime = $jcUpsell->getAutoScrollTime();
    $DisplayDirection = $jcUpsell->getDisplayDirection();
    $SliderScrollEffekt = $jcUpsell->getSliderScrollEffekt();
?>

<?php if('0'== $SliderActivation) :?> 
<!--
    Keine Aktivierung, der normale Inhalt wird geladen
-->
    <?php if(count($this->getItemCollection()->getItems())): ?>
    <div class="box-collateral box-up-sell">
        <h2><?php echo $this->__('You may also be interested in the following product(s)') ?></h2>
        <table class="products-grid" id="upsell-product-table">
        <?php // $this->setColumnCount(5); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
        <?php $this->resetItemsIterator() ?>
        <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
            <tr>
            <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
                <?php if($_link=$this->getIterableItem()): ?>
                <td>
                    <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image">
                        <img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(125) ?>" width="125" height="125" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" />
                    </a>
                    <h3 class="product-name">
                        <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>">
                            <?php echo $this->htmlEscape($_link->getName()) ?>
                        </a>
                    </h3>
                    <?php echo $this->getPriceHtml($_link, true, '-upsell') ?>
                    <?php echo $this->getReviewsSummaryHtml($_link) ?>
                </td>
                <?php else: ?>
                <td class="empty">&nbsp;</td>
                <?php endif; ?>
            <?php endfor; ?>
            </tr>
        <?php endfor; ?>
        </table>
        <script type="text/javascript">decorateTable('upsell-product-table')</script>
    </div>
    <?php endif ?>
<?php else: ?>
<!--
    Aktivierung, der neue Inhalt wird geladen
-->
    <script type="text/javascript">
        jQuery.easing['BounceEaseOut'] = function(p, t, b, c, d) {
            if ((t/=d) < (1/2.75)) {
                return c*(7.5625*t*t) + b;
            } else if (t < (2/2.75)) {
                return c*(7.5625*(t-=(1.5/2.75))*t + .75) + b;
            } else if (t < (2.5/2.75)) {
                return c*(7.5625*(t-=(2.25/2.75))*t + .9375) + b;
            } else {
                return c*(7.5625*(t-=(2.625/2.75))*t + .984375) + b;
            }
        };

        function mycarousel_initCallback(carousel){
            // Disable autoscrolling if the user clicks the prev or next button.
            carousel.buttonNext.bind('click', function() {
                carousel.startAuto(0);
            });
            carousel.buttonPrev.bind('click', function() {
                carousel.startAuto(0);
            });
                
            // Pause autoscrolling if the user moves with the cursor over the clip.
            carousel.clip.hover(function() {carousel.stopAuto();}, function() {carousel.startAuto();});
        }; 

        jQuery(document).ready(function() {
            jQuery('#mycarousel-upsell').jcarousel({
                <?php echo '1'==$SliderScrollEffekt ? 'easing: \'BounceEaseOut\'' : 'easing: \'swing\'' ?>
                ,animation:<?php echo $ScrollSpeed ?>
                <?php echo '1'==$SliderCircular ? ',wrap: \'circular\'' : '' ?>
                <?php echo 'vertical'==$SliderAlignment ? ',vertical: true' : '' ?>
                ,scroll:<?php echo $ItemCountScroll ?>
                <?php echo '0' != $AutoScrollTime ? ',auto:'.$AutoScrollTime.',initCallback: mycarousel_initCallback' : '' ?>
                <?php echo '0' != $AutoScrollTime && '1'!=$SliderCircular ? ',wrap: \'last\'' : '' ?>
                <?php echo '1'==$DisplayDirection ? ',rtl: true' : '' ?>
            });
        });
    </script>

    <div class="box-collateral box-up-sell">
        <h4>
            <?php echo $this->__('JCSLIDER UPSELL') ?>
        </h4>
        <div class="jcarousel-skin-tango">
            <div class="jcarousel-container jcarousel-container-horizontal" style="position: relative; display: block;">
                <div class="jcarousel-clip jcarousel-clip-horizontal" style="overflow: hidden; position: relative;">
                    <ul id="mycarousel-upsell" class="jcarousel-skin-tango">
                    <?php $this->resetItemsIterator() ?>
                    <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
                        <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
                            <?php if($_link=$this->getIterableItem()): ?>
                            <li>
                                <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image">
                                    <img src="<?php echo $this->helper('catalog/image')->init($_link, 'thumbnail')->resize(75) ?>" width="75" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image" />
                                </a>
                                <div class="product-shop">
                                    <h5>
                                        <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>">
                                            <?php echo $this->htmlEscape($_link->getName()) ?>
                                        </a>
                                    </h5>
                                    <?php echo $this->getPriceHtml($_link, true, '-upsell') ?>
                                    <?php echo $this->getReviewsSummaryHtml($_link) ?>
                                </div>
                            </li>
                            <?php endif; ?>
                        <?php endfor; ?>
                    <?php endfor; ?>
                    </ul>
                </div>
                    <div class="jcarousel-prev" style="display: block;"></div>
                    <div class="jcarousel-next" style="display: block;"></div>
            </div>
        </div>
    </div>

<?php endif; ?>