<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category           Netresearch
 * @package            Netresearch_JCarouselSlider
 * @author               Dandy Umlauft <dandy.umlauft@netresearch.de>
 * @copyright           Copyright (c) 2011 Dandy Umlauft | Netresearch GmbH & Co.KG (http://www.netresearch.de)
 * @license               http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
    $jcCrosssell = $this->jcCrosssell;
    $SliderActivation = $jcCrosssell->getSliderActivation();
    $ItemCountScroll = $jcCrosssell->getItemCountScroll();
    $ScrollSpeed = $jcCrosssell->getScrollSpeed();
    $SliderAlignment = $jcCrosssell->getSliderAlignment();
    $SliderCircular = $jcCrosssell->getSliderCircular();
    $AutoScrollTime = $jcCrosssell->getAutoScrollTime();
    $DisplayDirection = $jcCrosssell->getDisplayDirection();
    $SliderScrollEffekt = $jcCrosssell->getSliderScrollEffekt();
?>
<?php if($this->getItemCount()): ?>
    <div class="col-1 crossell">
        <h4><?php echo $this->__('JCSLIDER CROSSSELL') ?></h4>
        
        <?php if('1'== $SliderActivation) :?> 
        <script type="text/javascript">
            jQuery.easing['BounceEaseOut'] = function(p, t, b, c, d) {
                if ((t/=d) < (1/2.75)) {
                    return c*(7.5625*t*t) + b;
                } else if (t < (2/2.75)) {
                    return c*(7.5625*(t-=(1.5/2.75))*t + .75) + b;
                } else if (t < (2.5/2.75)) {
                    return c*(7.5625*(t-=(2.25/2.75))*t + .9375) + b;
                } else {
                    return c*(7.5625*(t-=(2.625/2.75))*t + .984375) + b;
                }
            };

            function mycarousel_initCallback(carousel){
                // Disable autoscrolling if the user clicks the prev or next button.
                carousel.buttonNext.bind('click', function() {
                    carousel.startAuto(0);
                });
                carousel.buttonPrev.bind('click', function() {
                    carousel.startAuto(0);
                });
            
                // Pause autoscrolling if the user moves with the cursor over the clip.
                carousel.clip.hover(function() {carousel.stopAuto();}, function() {carousel.startAuto();});
            }; 

            jQuery(document).ready(function() {
                jQuery('#mycarousel-crosssell').jcarousel({
                    <?php echo '1'==$SliderScrollEffekt ? 'easing: \'BounceEaseOut\'' : 'easing: \'swing\'' ?>
                    ,animation:<?php echo $ScrollSpeed ?>
                    <?php echo '1'==$SliderCircular ? ',wrap: \'circular\'' : '' ?>
                    <?php echo 'vertical'==$SliderAlignment ? ',vertical: true' : '' ?>
                    ,scroll:<?php echo $ItemCountScroll ?>
                    <?php echo '0' != $AutoScrollTime ? ',auto:'.$AutoScrollTime.',initCallback: mycarousel_initCallback' : '' ?>
                    <?php echo '0' != $AutoScrollTime && '1'!=$SliderCircular ? ',wrap: \'last\'' : '' ?>
                    <?php echo '1'==$DisplayDirection ? ',rtl: true' : '' ?>
                });
            });
        </script>
        
            <div class="jcarousel-skin-tango">
                <div class="jcarousel-container jcarousel-container-horizontal" style="position: relative; display: block;">
                    <div class="jcarousel-clip jcarousel-clip-horizontal" style="overflow: hidden; position: relative;">
                        <ul id="mycarousel-crosssell" class="jcarousel-skin-tango">
                        <?php else: ?>
                        <ul class="generic-product-list">
                        <?php endif; ?>
                        <?php foreach ($this->getItems() as $_item): ?>
                            <li>
                                <a href="<?php echo $_item->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(75); ?>" width="75" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image" /></a>
                                <div class="product-shop">
                                    <h5><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></h5>
                                    <?php echo $this->getPriceHtml($_item, true) ?>
                                    <button class="form-button" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')" type="button"><span><?php echo $this->__('Add to Cart') ?></span></button><br/>
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <small><a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="link-cart"><?php echo $this->__('Add to Wishlist') ?></a></small>
                                    <?php endif; ?>
                                    <?php if($_compareUrl=$this->getAddToCompareUrl($_item)): ?><br/>
                                    <small><a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add to Compare') ?></a></small>
                                    <?php endif; ?>
                                </div>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                    <?php if('1'== $SliderActivation) :?>  
                    </div>
                    <div class="jcarousel-prev" style="display: block;"></div>
                    <div class="jcarousel-next" style="display: block;"></div>
                </div>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>